### ISSUE TITLE
Combine call to the toolkit 

### ISSUE THREAD

**Issue by martijnvanbreden** [Pantheon-Research/pthtoolkit#4]
The toolkit offers possibilities to combine several calls to IBM i programms in a single xml. 

[Here](https://github.com/IBM/xmlservice/tree/master/docs/wiki-dump) you'll find documentation about it (i.e. generic-interface) The documentation layout is not very pretty, but it works. 

I'd suggest we investigate whether the toolkit allready offers support to combine calls or else build it into the PthToolkit wrapper.

**Comment by jvedev** [comment]
done
